version: '3.9'
services:
  database:
    image: postgres:15.3
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: