@url=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNscTdpOGs2NDAwMDA4dWFocWVmbmNnN2ciLCJlbWFpbCI6InNhbXVlbEBlbWFpbC5jb20iLCJuYW1lIjoiU2FtdWVsIFJvZHJpZ3VlcyIsImlhdCI6MTcwMzEzMTg2MH0.mUnQC-_e5WKgol7eAmyMP2McoFEEiydQpbDeUbKYpUc

GET {{url}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}
