@url=http://localhost:3000
@Bearer=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsb3MzNG40YjAwMDBxOGJ2bHR5NWttcmoiLCJlbWFpbCI6InNhbXVlbEBlbWFpbC5jb20iLCJuYW1lIjoiU2FtdWVsIFJvZHJpZ3VlcyIsImlhdCI6MTcwMDE0MzE4NH0.VO4ug0kIfu3nxsFMtVaYgT6JIKDqGEYIA2Ga3bG5Spw


DELETE {{url}}/api/users/logout
Content-Type: application/json
Cookie: access_token={{Bearer}}
